[package]
name = "row"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "9.0.2"
rand = "0.8"
paste = "^1.0"
datafusion-jit = { path = "../datafusion-jit" }
